version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    restart: always
    networks:
      - nodenetwork
    ports:
      - "8080:80"
  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm run app
    networks:
      - nodenetwork
    tty: true
    depends_on: 
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenetwork
networks:
  nodenetwork:
    driver: bridge
